name: Thank issue closer

on:
  issues:
    types: closed

jobs:
  thank-opener:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue comment "$NUMBER" --body "Thanks for closing things out :broom:"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
