name: Update README

on:
  schedule:
    # Every Monday
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repo to main branch
      uses: actions/checkout@v4.1.2
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 21.x
        node-version-file: package.json
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Generate new README file
      run: node index.js
    - name: Commit and push updated README
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrest.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'Automated README.md update'
        files: README.md
