name: README PR

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/readme-build.yml
