name: Update README

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed
  schedule:
    # Everyday at 9am UTC
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to main branch
        uses: actions/checkout@v4.1.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
      - run: npm install
      - name: Generate new README file
        run: node index.js
      - name: Commit and push updated README
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "main"
          commit-message: "Automated README.md update"
          force-add: "true"
          files: README.md
          name: Connie Nguyen
          email: connienguyen@users.noreply.github.com
