name: Test workflow with inputs

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        default: 'Hello world'
        required: true
        type: string

jobs:
  parrot:
    strategy:
      matrix:
        message: ['Default message', '${{ inputs.message }}']
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.message }}

  complete:
    runs-on: ubuntu-latest
    needs:
      - parrot
    steps:
      - run: echo all done
